FROM node:20-alpine AS builder
WORKDIR /app
COPY api-gateway/package*.json ./
RUN npm ci
COPY api-gateway/ .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package*.json ./
COPY common/protos/ /common/protos/

EXPOSE 3000
CMD ["node", "dist/main"]
